name: Algorithm Performance Benchmarks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  # Allow manual triggering
  workflow_dispatch:
  # Run weekly to track long-term changes
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight on Sunday

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Only install the packages needed for benchmarking
        pip install matplotlib numpy pytest pytest-cov
        
    - name: Create Python package structure
      run: |
        # Create an empty __init__.py file to make py directory a package
        touch py/__init__.py
        
    - name: Ensure benchmark directory exists
      run: |
        mkdir -p benchmark-results
        mkdir -p py/benchmark-results
        
    - name: Run benchmarks
      run: |
        # Change to the root directory
        cd $GITHUB_WORKSPACE
        
        # Add the current directory to PYTHONPATH so Python can find the modules
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
        
        # Run the benchmark script
        cd py
        python -m benchmarks.benchmark_algorithms all
        
    - name: Collect results
      run: |
        # Create directory if it doesn't exist
        mkdir -p benchmark-results
        
        # Copy benchmark results from py directory
        cp -r py/benchmark-results/* benchmark-results/ 2>/dev/null || true
        
        # Find any PNG files and copy them too
        find py -name "*.png" -exec cp {} benchmark-results/ \; 2>/dev/null || true
        
        # Create a valid benchmark file if it doesn't exist or is invalid
        if [ ! -f benchmark-results/github_action_benchmark.json ]; then
          echo '[]' > benchmark-results/github_action_benchmark.json
        fi
        
        # Check if the file is a valid JSON array
        if ! python -c "import json; json.load(open('benchmark-results/github_action_benchmark.json'))"; then
          echo '[]' > benchmark-results/github_action_benchmark.json
        fi
        
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results/
        
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Algorithm Performance Benchmarks
        tool: 'customBiggerIsBetter'
        output-file-path: benchmark-results/github_action_benchmark.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # Alert threshold:
        alert-threshold: '150%'
        comment-on-alert: true
        fail-on-alert: true
        # GitHub pages branch to store benchmark results
        gh-pages-branch: gh-pages
        
    - name: Check for performance regression
      id: check-regression
      run: |
        if [ -f benchmark-results/regression_detected.txt ]; then
          echo "regression=true" >> $GITHUB_OUTPUT
          echo "::warning::Performance regression detected!"
        else
          echo "regression=false" >> $GITHUB_OUTPUT
        fi
        
    # Send webhook notification if regression is detected
    - name: Send webhook notification on regression
      if: steps.check-regression.outputs.regression == 'true'
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: https://hook.eu1.make.com/rewf3vebmbx4q1w6r2iril729efe2xzt
        webhook_secret: ${{ secrets.WEBHOOK_SECRET || '' }}
        data: >
          {
            "type": "performance_regression",
            "repository": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "workflow_run_id": "${{ github.run_id }}",
            "workflow_run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "detected_at": "${{ github.event.repository.updated_at }}",
            "branch": "${{ github.ref_name }}",
            "action_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
        
    # Create GitHub issue for significant regressions
    - name: Create GitHub issue for regression
      if: steps.check-regression.outputs.regression == 'true'
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/REGRESSION_ISSUE_TEMPLATE.md
        update_existing: true
        search_existing: open
